### ISSUE TITLE
custom action doesn't parse matched file as the first parameter

### ISSUE THREAD

**Issue by robbielj** [mshorts/belvedere#55]
According to help topics,custom action will run executives with matched file as first parameter of the executable. 
But when I use a batch file, %1 doesn't return file name.

I am wondering whether this is a bug or I have got something wrong .

**Comment by mshorts** [comment]
Looks like there were a couple things going on here:
1. Paths (for both the file and the executable) that had spaces could cause problems
2. The working directory of the custom executable was that of the Belvedere rather than the custom executable (which is what I believe it should be).

I've addressed both with new code.
